# Generated by Django 3.2.4 on 2022-08-26 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='', max_length=6)),
                ('modelo', models.CharField(max_length=6)),
                ('codigo', models.CharField(max_length=6)),
                ('motor', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=30)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('dni', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone1', models.CharField(default='', max_length=10)),
                ('gener', models.CharField(default='', max_length=2)),
                ('country', models.CharField(default='', max_length=10)),
                ('state', models.CharField(default='', max_length=10)),
                ('email', models.CharField(default='', max_length=30)),
                ('dob', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.bus')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dni', models.PositiveIntegerField()),
                ('dob', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('gener', models.CharField(max_length=1)),
                ('license', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.trip')),
                ('seat1', models.CharField(max_length=50)),
                ('seat2', models.CharField(max_length=50)),
                ('seat3', models.CharField(max_length=50)),
                ('seat4', models.CharField(max_length=50)),
                ('seat5', models.CharField(max_length=50)),
                ('seat6', models.CharField(max_length=50)),
                ('seat7', models.CharField(max_length=50)),
                ('seat8', models.CharField(max_length=50)),
                ('seat9', models.CharField(max_length=50)),
                ('seat10', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('seats', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.seats')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.passenger')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
        ),
    ]
