# Generated by Django 3.2.4 on 2022-08-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='', max_length=6)),
                ('modelo', models.CharField(max_length=6)),
                ('codigo', models.CharField(max_length=6)),
                ('motor', models.CharField(max_length=30)),
                ('chasis', models.CharField(max_length=30)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('dni', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(default='', max_length=50)),
                ('phone1', models.CharField(default='', max_length=10)),
                ('gener', models.CharField(default='', max_length=2)),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('email', models.CharField(default='', max_length=30)),
                ('dob', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat1', to='api.passenger')),
                ('seat10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat10', to='api.passenger')),
                ('seat2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat2', to='api.passenger')),
                ('seat3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat3', to='api.passenger')),
                ('seat4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat4', to='api.passenger')),
                ('seat5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat5', to='api.passenger')),
                ('seat6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat6', to='api.passenger')),
                ('seat7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat7', to='api.passenger')),
                ('seat8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat8', to='api.passenger')),
                ('seat9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat9', to='api.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('arriveTime', models.DateTimeField(blank=True, null=True)),
                ('departureTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='UserAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.bus')),
                ('name', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dni', models.PositiveIntegerField()),
                ('dob', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('phone1', models.CharField(max_length=10)),
                ('phone2', models.CharField(max_length=10)),
                ('gener', models.CharField(max_length=1)),
                ('license', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(default='A', max_length=10)),
            ],
        ),
    ]
