# Generated by Django 3.2.4 on 2022-08-27 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220827_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.bus'),
        ),
        migrations.AddField(
            model_name='seats',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
        ),
    ]
