# Generated by Django 3.2.4 on 2022-08-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220826_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
    ]
