# Generated by Django 3.2.4 on 2022-08-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220826_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default='A', max_length=10),
        ),
    ]
