# Generated by Django 3.2.4 on 2022-08-27 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220827_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='routeName',
            new_name='description',
        ),
        migrations.AddField(
            model_name='book',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.passenger'),
        ),
        migrations.AddField(
            model_name='book',
            name='seats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.seats'),
        ),
        migrations.AddField(
            model_name='book',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.trip'),
        ),
    ]
